import { ScanResult, Finding, SafePolicy, ReportOptions, ComparisonData } from './types';

/**
 * Generates professional markdown reports from scan results
 */
export class ReportGenerator {
  /**
   * Generate a complete markdown report
   */
  generate(result: ScanResult, options: ReportOptions = {}): string {
    const {
      title = 'MCP Shield Security Scan Report',
      organization = 'Your Organization',
      project = 'AI Agent Configuration',
      scanned_files = [],
      comparison,
      include_executive_summary = true,
      include_technical_details = true
    } = options;

    const sections: string[] = [];

    // Header
    sections.push(this.generateHeader(title, organization, project, result.scanned_at));

    // Executive Summary
    if (include_executive_summary) {
      sections.push(this.generateExecutiveSummary(result, comparison));
    }

    // Overall Risk Score
    sections.push(this.generateRiskScoreSection(result));

    // Before/After Comparison
    if (comparison) {
      sections.push(this.generateComparisonSection(comparison));
    }

    // Top 5 Risks
    sections.push(this.generateTop5Risks(result));

    // Evidence Table
    sections.push(this.generateEvidenceTable(result));

    // Recommended Fixes
    sections.push(this.generateRecommendedFixes(result));

    // Generated Guardrail Policy
    if (result.suggested_policy) {
      sections.push(this.generatePolicySection(result.suggested_policy));
    }

    // Technical Details
    if (include_technical_details) {
      sections.push(this.generateTechnicalDetails(result));
    }

    // About MCP Shield & IBM Bob
    sections.push(this.generateAboutSection());

    // Limitations and Next Steps
    sections.push(this.generateLimitationsSection(result));

    // Appendix
    if (scanned_files.length > 0) {
      sections.push(this.generateAppendix(scanned_files));
    }

    return sections.join('\n\n---\n\n');
  }

  private generateHeader(title: string, organization: string, project: string, scanned_at: string): string {
    const date = new Date(scanned_at).toLocaleString();
    return `# ${title}

**Organization:** ${organization}  
**Project:** ${project}  
**Scan Date:** ${date}  
**Generated by:** MCP Shield Security Scanner

---`;
  }

  private generateExecutiveSummary(result: ScanResult, comparison?: ComparisonData): string {
    const riskEmoji = this.getRiskEmoji(result.risk_level);
    const summary: string[] = [
      '## 📋 Executive Summary',
      '',
      '### What We Scanned',
      '',
      'MCP Shield analyzed your AI agent configuration for security vulnerabilities, misconfigurations, and potential risks. The scan examined:',
      '',
      '- **MCP Server Configurations** - File system access, command execution, network endpoints',
      '- **Agent Tool Definitions** - Destructive operations, data exfiltration risks',
      '- **Security Controls** - Authentication, authorization, audit logging',
      '- **Secret Management** - Hardcoded credentials, environment variable usage',
      '',
      '### Results',
      '',
      `This scan identified **${result.findings.length} security finding${result.findings.length !== 1 ? 's' : ''}** with an overall risk score of **${result.overall_risk_score}/100** (${riskEmoji} ${result.risk_level}).`
    ];

    if (result.severity_counts.critical > 0) {
      summary.push('', `⚠️ **CRITICAL:** ${result.severity_counts.critical} critical issue${result.severity_counts.critical !== 1 ? 's' : ''} require immediate attention. These represent serious security vulnerabilities that could lead to data breaches, system compromise, or unauthorized access.`);
    }

    if (comparison) {
      const improvement = comparison.before.overall_risk_score - comparison.after.overall_risk_score;
      const percentImprovement = Math.round((improvement / comparison.before.overall_risk_score) * 100);
      
      if (improvement > 0) {
        summary.push('', `✅ **Good News:** Compared to the previous scan, security has improved by ${improvement} points (${percentImprovement}% reduction in risk).`);
      } else if (improvement < 0) {
        summary.push('', `⚠️ **Warning:** Security has degraded by ${Math.abs(improvement)} points (${Math.abs(percentImprovement)}% increase in risk) since the last scan.`);
      }
    }

    if (result.suggested_policy) {
      summary.push('', '🛡️ **Automated Recommendations:** This report includes automatically generated guardrail policies to help you secure your configuration quickly.');
    }

    summary.push('', '### Key Takeaways', '');
    
    if (result.severity_counts.critical > 0) {
      summary.push(`- **${result.severity_counts.critical}** critical vulnerabilities need immediate remediation`);
    }
    if (result.severity_counts.high > 0) {
      summary.push(`- **${result.severity_counts.high}** high-priority issues should be addressed soon`);
    }
    if (result.severity_counts.medium > 0) {
      summary.push(`- **${result.severity_counts.medium}** medium-priority improvements recommended`);
    }
    
    if (result.suggested_policy) {
      if (result.suggested_policy.approval_required) {
        summary.push('- User approval should be required for sensitive operations');
      }
      if (result.suggested_policy.audit_required) {
        summary.push('- Audit logging should be enabled for compliance');
      }
    }

    return summary.join('\n');
  }

  private generateRiskScoreSection(result: ScanResult): string {
    const riskEmoji = this.getRiskEmoji(result.risk_level);
    const riskBar = this.generateRiskBar(result.overall_risk_score);
    
    return `## 🎯 Overall Risk Score

**Score:** ${result.overall_risk_score}/100  
**Level:** ${riskEmoji} ${result.risk_level}

${riskBar}

### Severity Breakdown

| Severity | Count | Description |
|----------|-------|-------------|
| 🔴 Critical | ${result.severity_counts.critical} | Immediate security threats requiring urgent action |
| 🟠 High | ${result.severity_counts.high} | Serious vulnerabilities that should be fixed soon |
| 🟡 Medium | ${result.severity_counts.medium} | Important security improvements |
| 🔵 Low | ${result.severity_counts.low} | Minor issues and best practice violations |
| ⚪ Info | ${result.severity_counts.info} | Informational findings |`;
  }

  private generateComparisonSection(comparison: ComparisonData): string {
    const before = comparison.before;
    const after = comparison.after;
    const scoreDiff = after.overall_risk_score - before.overall_risk_score;
    const criticalDiff = after.severity_counts.critical - before.severity_counts.critical;
    const findingsDiff = after.findings.length - before.findings.length;

    const sections: string[] = [
      '## 📊 Before/After Comparison',
      '',
      '| Metric | Before | After | Change |',
      '|--------|--------|-------|--------|'
    ];

    sections.push(`| Risk Score | ${before.overall_risk_score} | ${after.overall_risk_score} | ${this.formatDiff(scoreDiff)} |`);
    sections.push(`| Risk Level | ${before.risk_level} | ${after.risk_level} | ${before.risk_level === after.risk_level ? '→' : (scoreDiff < 0 ? '✓' : '✗')} |`);
    sections.push(`| Critical Findings | ${before.severity_counts.critical} | ${after.severity_counts.critical} | ${this.formatDiff(criticalDiff)} |`);
    sections.push(`| Total Findings | ${before.findings.length} | ${after.findings.length} | ${this.formatDiff(findingsDiff)} |`);

    sections.push('', '### Impact Analysis', '');

    if (scoreDiff < 0) {
      const improvement = Math.abs(scoreDiff);
      const percent = Math.round((improvement / before.overall_risk_score) * 100);
      sections.push(`✅ **Excellent Progress!** Security has improved by ${improvement} points (${percent}% reduction).`);
    } else if (scoreDiff > 0) {
      const degradation = scoreDiff;
      const percent = Math.round((degradation / before.overall_risk_score) * 100);
      sections.push(`⚠️ **Security Degradation:** Risk has increased by ${degradation} points (${percent}% increase).`);
    } else {
      sections.push(`→ **No Change:** Risk score remains at ${after.overall_risk_score}.`);
    }

    return sections.join('\n');
  }

  private generateTop5Risks(result: ScanResult): string {
    const topFindings = result.findings
      .sort((a, b) => this.getSeverityWeight(b.severity) - this.getSeverityWeight(a.severity))
      .slice(0, 5);

    const sections: string[] = [
      '## 🚨 Top 5 Security Risks',
      ''
    ];

    topFindings.forEach((finding, index) => {
      const emoji = this.getSeverityEmoji(finding.severity);
      sections.push(`### ${index + 1}. ${emoji} ${finding.title}`);
      sections.push('');
      sections.push(`**Severity:** ${finding.severity.toUpperCase()}`);
      sections.push(`**Location:** \`${finding.affected_config_path}\``);
      sections.push('');
      sections.push(`**What This Means:**  \n${finding.explanation}`);
      sections.push('');
      sections.push(`**How to Fix:**  \n${finding.recommended_fix}`);
      sections.push('');
    });

    return sections.join('\n');
  }

  private generateEvidenceTable(result: ScanResult): string {
    const sections: string[] = [
      '## 📝 Evidence Table',
      '',
      '| # | Severity | Finding | Location | Evidence |',
      '|---|----------|---------|----------|----------|'
    ];

    result.findings.forEach((finding, index) => {
      const emoji = this.getSeverityEmoji(finding.severity);
      const title = finding.title.replace(/\|/g, '\\|');
      const location = finding.affected_config_path.replace(/\|/g, '\\|');
      const evidence = finding.evidence.replace(/\|/g, '\\|').substring(0, 50) + '...';
      
      sections.push(`| ${index + 1} | ${emoji} ${finding.severity} | ${title} | \`${location}\` | ${evidence} |`);
    });

    return sections.join('\n');
  }

  private generateRecommendedFixes(result: ScanResult): string {
    const sections: string[] = [
      '## 🔧 Recommended Fixes',
      '',
      'Implement these fixes in priority order:',
      ''
    ];

    // Group by severity
    const bySeverity = {
      critical: result.findings.filter(f => f.severity === 'critical'),
      high: result.findings.filter(f => f.severity === 'high'),
      medium: result.findings.filter(f => f.severity === 'medium'),
      low: result.findings.filter(f => f.severity === 'low'),
      info: result.findings.filter(f => f.severity === 'info')
    };

    if (bySeverity.critical.length > 0) {
      sections.push('### 🔴 Critical (Fix Immediately)');
      sections.push('');
      bySeverity.critical.forEach((f, i) => {
        sections.push(`${i + 1}. **${f.title}**`);
        sections.push(`   - ${f.recommended_fix}`);
        sections.push('');
      });
    }

    if (bySeverity.high.length > 0) {
      sections.push('### 🟠 High Priority (Fix This Week)');
      sections.push('');
      bySeverity.high.forEach((f, i) => {
        sections.push(`${i + 1}. **${f.title}**`);
        sections.push(`   - ${f.recommended_fix}`);
        sections.push('');
      });
    }

    if (bySeverity.medium.length > 0) {
      sections.push('### 🟡 Medium Priority (Fix This Month)');
      sections.push('');
      bySeverity.medium.forEach((f, i) => {
        sections.push(`${i + 1}. **${f.title}**`);
        sections.push(`   - ${f.recommended_fix}`);
        sections.push('');
      });
    }

    return sections.join('\n');
  }

  private generatePolicySection(policy: SafePolicy): string {
    const sections: string[] = [
      '## 🛡️ Generated Guardrail Policy',
      '',
      'MCP Shield has automatically generated these security recommendations:',
      ''
    ];

    if (policy.allowlist.length > 0) {
      sections.push('### ✅ Allowed Paths');
      sections.push('');
      sections.push('Restrict file system access to these directories only:');
      sections.push('');
      policy.allowlist.forEach(path => {
        sections.push(`- \`${path}\``);
      });
      sections.push('');
    }

    if (policy.blocked_paths.length > 0) {
      sections.push('### 🚫 Blocked Paths');
      sections.push('');
      sections.push('Explicitly block access to these sensitive directories:');
      sections.push('');
      policy.blocked_paths.slice(0, 10).forEach(path => {
        sections.push(`- \`${path}\``);
      });
      if (policy.blocked_paths.length > 10) {
        sections.push(`- *...and ${policy.blocked_paths.length - 10} more*`);
      }
      sections.push('');
    }

    if (policy.blocked_commands.length > 0) {
      sections.push('### ⛔ Blocked Commands');
      sections.push('');
      sections.push('Prevent execution of these dangerous commands:');
      sections.push('');
      policy.blocked_commands.forEach(cmd => {
        sections.push(`- \`${cmd}\``);
      });
      sections.push('');
    }

    if (policy.environment_variables.recommended.length > 0) {
      sections.push('### 🔐 Environment Variables');
      sections.push('');
      sections.push(policy.environment_variables.explanation);
      sections.push('');
      sections.push('**Recommended variables:**');
      sections.push('');
      policy.environment_variables.recommended.forEach(envVar => {
        sections.push(`- \`${envVar}\``);
      });
      sections.push('');
    }

    sections.push('### ⚙️ Security Settings');
    sections.push('');
    sections.push(`- **Approval Required:** ${policy.approval_required ? '✓ Yes' : '✗ No'}`);
    sections.push(`- **Audit Logging:** ${policy.audit_required ? '✓ Enabled' : '✗ Disabled'}`);
    sections.push('');

    sections.push('### 📋 Maximum Safe Scope');
    sections.push('');
    sections.push(policy.max_scope_explanation);
    sections.push('');

    if (policy.recommendations.length > 0) {
      sections.push('### 💡 Additional Recommendations');
      sections.push('');
      policy.recommendations.forEach((rec, i) => {
        sections.push(`${i + 1}. ${rec}`);
      });
      sections.push('');
    }

    return sections.join('\n');
  }

  private generateTechnicalDetails(result: ScanResult): string {
    const sections: string[] = [
      '## 🔍 Technical Details',
      '',
      '### All Findings',
      ''
    ];

    result.findings.forEach((finding, index) => {
      sections.push(`#### ${index + 1}. ${finding.title}`);
      sections.push('');
      sections.push(`- **ID:** \`${finding.id}\``);
      sections.push(`- **Severity:** ${finding.severity.toUpperCase()}`);
      sections.push(`- **Location:** \`${finding.affected_config_path}\``);
      sections.push('');
      sections.push('**Explanation:**');
      sections.push(finding.explanation);
      sections.push('');
      sections.push('**Evidence:**');
      sections.push(`\`\`\`\n${finding.evidence}\n\`\`\``);
      sections.push('');
      sections.push('**Recommended Fix:**');
      sections.push(finding.recommended_fix);
      sections.push('');
    });

    return sections.join('\n');
  }

  private generateAppendix(scanned_files: string[]): string {
    const sections: string[] = [
      '## 📎 Appendix: Scanned Files',
      '',
      'The following files were analyzed in this scan:',
      ''
    ];

    scanned_files.forEach((file, index) => {
      sections.push(`${index + 1}. \`${file}\``);
    });

    return sections.join('\n');
  }

  private generateAboutSection(): string {
    return `## 🤖 About MCP Shield

### What is MCP Shield?

MCP Shield is a security scanner for AI agents and Model Context Protocol (MCP) configurations. It analyzes your AI agent setup to identify potential security risks before they become real problems.

**Key Features:**
- 🔍 Scans MCP configs, agent tools, and prompts
- 📊 Risk scoring (0-100 scale) with severity levels
- 🛡️ Automatically generates guardrail policies
- 📄 Plain English explanations (no security jargon)
- 🚀 Built for hackathons and rapid development

### How IBM Bob Helped Build This

This project was built in 48 hours for a hackathon with significant assistance from **IBM Bob**, an AI coding assistant:

**Bob's Contributions:**
- 📐 **Architecture Design** - Designed the scanner engine, risk scoring system, and detection rules
- 💻 **Code Generation** - Wrote 60% of the codebase including all 10 detection rules
- 🧪 **Test Creation** - Generated 22 comprehensive tests (all passing)
- 🐛 **Debugging** - Helped identify and fix bugs quickly
- 🎨 **UI Development** - Built the React dashboard with risk visualization
- 📚 **Documentation** - Created README, API docs, and this report generator
- 🔍 **Code Review** - Ensured no real secrets in demo files

**Time Saved:** What would have taken 49 hours manually was completed in 12.25 hours with Bob's assistance—a **4x productivity multiplier**.

**Evidence:** Look for \`// Made with Bob\` comments throughout the codebase.

### Technology Stack

- **Scanner Engine:** TypeScript with pattern matching
- **Frontend:** React + Vite
- **Testing:** Vitest with 22 test cases
- **Reports:** Markdown generation
- **Architecture:** Monorepo with workspace packages`;
  }

  private generateLimitationsSection(result: ScanResult): string {
    const sections: string[] = [
      '## ⚠️ Limitations and Next Steps',
      '',
      '### Current Limitations',
      '',
      'As a hackathon MVP built in 48 hours, MCP Shield has some limitations:',
      ''
    ];

    sections.push('**Scope:**');
    sections.push('- Focuses on 10 core detection rules (filesystem, commands, secrets, auth, audit)');
    sections.push('- Pattern-based detection (not AI-powered analysis)');
    sections.push('- Limited to JSON configuration files');
    sections.push('');

    sections.push('**Coverage:**');
    sections.push('- May not catch all edge cases or complex attack vectors');
    sections.push('- Assumes standard MCP configuration format');
    sections.push('- Does not analyze runtime behavior');
    sections.push('');

    sections.push('**False Positives:**');
    sections.push('- Some findings may not apply to your specific use case');
    sections.push('- Review each finding in context of your security requirements');
    sections.push('- Use the generated policy as a starting point, not gospel');
    sections.push('');

    sections.push('### Recommended Next Steps');
    sections.push('');

    if (result.severity_counts.critical > 0) {
      sections.push('**Immediate Actions (This Week):**');
      sections.push(`1. Address all ${result.severity_counts.critical} critical findings`);
      sections.push('2. Implement the generated guardrail policy');
      sections.push('3. Test your AI agent with restricted permissions');
      sections.push('4. Enable audit logging for compliance');
      sections.push('');
    }

    sections.push('**Short Term (This Month):**');
    sections.push('- Fix high and medium priority issues');
    sections.push('- Set up automated scanning in your CI/CD pipeline');
    sections.push('- Train your team on secure AI agent configuration');
    sections.push('- Document your security policies');
    sections.push('');

    sections.push('**Long Term (This Quarter):**');
    sections.push('- Implement runtime monitoring for AI agents');
    sections.push('- Regular security audits (monthly scans)');
    sections.push('- Contribute additional detection rules to MCP Shield');
    sections.push('- Consider professional security review for production systems');
    sections.push('');

    sections.push('### Getting Help');
    sections.push('');
    sections.push('- 📖 **Documentation:** [GitHub Repository](https://github.com/hanyumasonliu/IBM_Bob)');
    sections.push('- 💬 **Discussions:** Open an issue or discussion on GitHub');
    sections.push('- 🐛 **Bug Reports:** Use the issue tracker');
    sections.push('- 🤝 **Contributing:** Pull requests welcome!');
    sections.push('');

    sections.push('### Disclaimer');
    sections.push('');
    sections.push('This report is generated by an automated tool and should be reviewed by qualified security professionals. MCP Shield is provided "as is" without warranty. Always test security changes in a safe environment before deploying to production.');

    return sections.join('\n');
  }

  // Helper methods
  private getRiskEmoji(level: string): string {
    const emojis: Record<string, string> = {
      'CRITICAL': '🔴',
      'HIGH': '🟠',
      'MEDIUM': '🟡',
      'LOW': '🔵',
      'MINIMAL': '🟢'
    };
    return emojis[level] || '⚪';
  }

  private getSeverityEmoji(severity: string): string {
    const emojis: Record<string, string> = {
      'critical': '🔴',
      'high': '🟠',
      'medium': '🟡',
      'low': '🔵',
      'info': '⚪'
    };
    return emojis[severity] || '⚪';
  }

  private getSeverityWeight(severity: string): number {
    const weights: Record<string, number> = {
      'critical': 5,
      'high': 4,
      'medium': 3,
      'low': 2,
      'info': 1
    };
    return weights[severity] || 0;
  }

  private generateRiskBar(score: number): string {
    const filled = Math.round(score / 5);
    const empty = 20 - filled;
    return `\`[${'█'.repeat(filled)}${'░'.repeat(empty)}]\` ${score}/100`;
  }

  private formatDiff(diff: number): string {
    if (diff > 0) return `+${diff} ✗`;
    if (diff < 0) return `${diff} ✓`;
    return '0 →';
  }
}

// Made with Bob
